### ISSUE TITLE
0.10.1: Error: ENOENT: no such file or directory, rename '/tmp/setup-wasm-pack/wasm-pack-v0.10.1-x86_64-unknown-linux-musl/wasm-pack' -> '/home/runner/.cargo/bin/wasm-pack' 

### ISSUE THREAD

**Issue by iceiix** [rustwasm/wasm-pack#1057]
## 🐛 Bug description
Hello, with the 0.10.1 update I'm seeing a new failure in my CI pipeline:

```
Searching the latest version of wasm-pack ...
Installing wasm-pack v0.10.1 ...
Downloading wasm-pack from https://github.com/rustwasm/wasm-pack/releases/download/v0.10.1/wasm-pack-v0.10.1-x86_64-unknown-linux-musl.tar.gz ...
Extracting wasm-pack to /tmp/setup-wasm-pack ...
/usr/bin/tar xz --warning=no-unknown-keyword -C /tmp/setup-wasm-pack -f /home/runner/work/_temp/0d295110-54c4-4869-99e9-38c7b03b7ade
Error: ENOENT: no such file or directory, rename '/tmp/setup-wasm-pack/wasm-pack-v0.10.1-x86_64-unknown-linux-musl/wasm-pack' -> '/home/runner/.cargo/bin/wasm-pack'
Done
```

This started occurring soon after the 0.10.1 release (example failing run: https://github.com/iceiix/stevenarella/runs/3518938444)

I'm using wasm-pack through https://github.com/jetli/wasm-pack-action like in my .github/workflows/build.yaml like so:

```yaml
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
```

#### 🤔 Expected Behavior
Rolling back to `version: 'v0.10.0'` resolved the CI failure (example successful run: https://github.com/iceiix/stevenarella/pull/605/checks?check_run_id=3518993593)

Can't say I understand how, but the change in wasm-pack 0.10.1 https://github.com/rustwasm/wasm-pack/commit/b1e67d3d22b17bcfe60d5d8258bd4609bcb9bf55 does appear to be related to naming, could it have broken an assumption in wasm-pack-action? (unclear if https://github.com/jetli/wasm-pack-action is actively maintained - last commit is from Mar 30, 2020, and there are several open pull requests - maybe I should switch to the alternative https://rustwasm.github.io/docs/wasm-bindgen/wasm-bindgen-test/continuous-integration.html#github-actions ? but I have a working workaround, just filing this in case someone else hits it or a fix is needed in this repo too)

#### 👟 Steps to reproduce
.github/workflows/build.yaml:

```yaml
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
```

#### 🌍 Your environment
wasm-pack version: 0.10.1
rustc version: 1.54.0
GitHub Actions

**Comment by drager** [comment]
Thanks for reporting! Could you try to rerun that action? https://github.com/iceiix/stevenarella/runs/3518938444 I had some problems with the release tar file a while there and perhaps your action ran when they were broken.

**Comment by PoignardAzur** [comment]
I've had the same problem on my CI, for the same reason. Re-running the CI now to check if it passes.

**Comment by PoignardAzur** [comment]
Still [getting the same error](https://github.com/linebender/druid/runs/3523472567?check_suite_focus=true):

```term
Run jetli/wasm-pack-action@v0.3.0
Searching the latest version of wasm-pack ...
Installing wasm-pack v0.10.1 ...
Downloading wasm-pack from https://github.com/rustwasm/wasm-pack/releases/download/v0.10.1/wasm-pack-v0.10.1-x86_64-apple-darwin.tar.gz ...
Extracting wasm-pack to /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/setup-wasm-pack ...
/usr/bin/tar xz -C /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/setup-wasm-pack -f /Users/runner/work/_temp/a9f86042-d116-4374-a878-4703699f4154
Error: ENOENT: no such file or directory, rename '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/setup-wasm-pack/wasm-pack-v0.10.1-x86_64-apple-darwin/wasm-pack' -> '/Users/runner/.cargo/bin/wasm-pack'
Done
```

In my case, CI uses MacOS:

```yaml

  test-stable-wasm:
    runs-on: macOS-latest
    name: cargo test (wasm32)
    steps:
      - uses: actions/checkout@v2

      - name: install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: latest

        # ...
```
