### ISSUE TITLE
Error: Cannot find module 'env'

### ISSUE THREAD

**Issue by EdgeKing810** [rustwasm/wasm-pack#1100]
## 🐛 Bug description
After running a `wasm-pack build --release --target nodejs`, when importing the generated js file from the `pkg/` folder in a NodeJS app, I'm getting the following error:

```bash
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'env'
```

#### 🤔 Expected Behavior

This line should not be in the generated js file:
```js
imports['env'] = require('env');
```

I do not know if this should be replaced by something else but it sure doesn't work by just removing this line.

#### 👟 Steps to reproduce

Easiest way to reproduce this would be to execute the following commands:
```bash
git clone https://github.com/EdgeKing810/kinesis-db
cd kinesis-db/
bash build-wasm.sh
cd api/
node index.js
```

Full error when doing a `import pkg from '../pkg/kinesis_db.js';` in my NodeJS app:
```bash
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'env'
Require stack:
- /home/edgeking810/Documents/Rust/kinesis-db/pkg/kinesis_db.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/edgeking810/Documents/Rust/kinesis-db/pkg/kinesis_db.js:2:18)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:190:29) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/edgeking810/Documents/Rust/kinesis-db/pkg/kinesis_db.js' ]
}

Node.js v17.2.0
```

I tried using other flags such as `--dev` or `--debug` but I face the same problem. Building without the `--target nodejs` flag is not feasible for me since I'll be using this wasm build in a NodeJS backend app, not for a frontend application with a bundler such as Webpack.

#### 🌍 My environment

```bash
# cargo --version
cargo 1.57.0 (b2e52d7ca 2021-10-21)
# rustc -V
rustc 1.57.0 (f1edd0429 2021-11-29)
```

Tried using the latest nightly Rust build too.

### Additional

This issue has initially been raised in #743, I'm just creating a new issue because this is a really blocking problem. I tried other solutions such as `rustwasmc` too but they all have some kind of issues.

Here's the `Cargo.toml` file I'm using as well in case that helps:

```toml
[package]
name = "kinesis-db"
description = "A secure, portable and fast database written in Rust for Kinesis API"
repository = "https://github.com/EdgeKing810/kinesis-db"
license = "MIT"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
regex = "1"
magic-crypt = "3.1.9"
wasm-bindgen = "0.2.74"
fastrand = "1.5.0"
blowfish = { version = "0.8", features = ["bcrypt"] }
base64 = { version = "0.13", default-features = false }
parking_lot_core = "=0.8.0"

[profile.release]
lto = true
opt-level = "z"
```

FYI, I've tried tweaking the `profile.release` section multiple times by adding/removing the `lto = true` line, and 'unsetting' the `opt-level` variable or by giving it the value `"s"` + testing with multiple flags.

Happy New Year :night_with_stars: in advance and I hope we get a fix soon for this issue :crossed_fingers:. Very grateful if anyone could help on this, thanks in advance!
