### ISSUE TITLE
Duplicate custom typescript section

### ISSUE THREAD

**Issue by DzenanJupic** [rustwasm/wasm-pack#1112]
## 🐛 Bug description
Apparently, mixing `wee_alloc`, `-Clinker-plugin-lto=yes`, and a custom typescript section leads to the custom typescript section being repeated multiple times in `_.d.ts`.

#### 🤔 Expected Behavior
The custom typescript section should only be included once in `_.d.ts`.

#### 👟 Steps to reproduce
```toml
# .cargo/config.toml
[target.wasm32-unknown-unknown]
rustflags = ["-Clinker-plugin-lto=yes"]
```
```toml
# Cargo.toml
[package]
name = "temp"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.79"
wee_alloc = "0.4.5"
```
```
// lib.rs
use wasm_bindgen::{prelude::wasm_bindgen};

#[global_allocator]
static ALLOC: wee_alloc::WeeAlloc = wee_alloc::WeeAlloc::INIT;

#[wasm_bindgen(typescript_custom_section)]
const _TS: &str = r#"
export type SomeThing = any;
"#;
```

`wasm-pack build`

<details>
<summary>pkg/temp.d.ts</summary>

```typescript
/* tslint:disable */
/* eslint-disable */

export type SomeThing = any;



export type SomeThing = any;



export type SomeThing = any;



export type SomeThing = any;



export type SomeThing = any;



export type SomeThing = any;



export type SomeThing = any;
```
</details>

#### 🌍 Your environment
```
rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
binary: rustc
commit-hash: 1e12aef3fab243407f9d71ba9956cb2a1bf105d5
commit-date: 2022-02-13
host: x86_64-pc-windows-msvc
release: 1.60.0-nightly
LLVM version: 13.0.0

AND

rustc 1.58.1 (db9d1b20b 2022-01-20)
binary: rustc
commit-hash: db9d1b20bba1968c1ec1fc49616d4742c1725b4b
commit-date: 2022-01-20
host: x86_64-pc-windows-msvc
release: 1.58.1
LLVM version: 13.0.0
```
```
wasm-pack 0.9.1
```
```
wasm-bindgen 0.2.78
```
