### ISSUE TITLE
Cannot build root crate with `-p` if `Cargo.toml` defines both a crate and a workspace

### ISSUE THREAD

**Issue by not-my-profile** [rustwasm/wasm-pack#1211]
At [ruff](https://github.com/charliermarsh/ruff/) we recently switched to a structure such as the following: The `Cargo.toml` in the top-level directory defines:

```toml
[workspace]
members = [
  "flake8_to_ruff",
  "ruff_dev",
  "ruff_cli",
]
default-members = [".", "ruff_cli"]

[package]
name = "ruff"
```

This results in `cargo build` by default building both the `ruff` and `ruff_cli` crates and `cargo build -p ruff` only building the `ruff` crate.

Attempting to pass the `-p ruff` option to `wasm-pack build` however fails with:

```
$ wasm-pack build --target web --out-dir playground/src/pkg -- -p ruff
Error: crate directory is missing a `Cargo.toml` file; is `-p` the wrong directory?
```

And that despite the `--help` claiming:

```
    <extra-options>...    List of extra options to pass to `cargo build`
```

which would imply that any option that can be passed to `cargo build` also can be passed to `wasm-pack build`.

(wasm-pack version 0.10.3)
