### ISSUE TITLE
error parsing `package.license`

### ISSUE THREAD

**Issue by DaniPopes** [rustwasm/wasm-pack#1238]
## 🐛 Bug description

wasm-pack fails parsing Cargo manifests where the `package.license` value is an object instead of a string. This happens when  using workspaces.

#### 🤔 Expected Behavior
Doesn't error

#### 👟 Steps to reproduce

- create a project with this Cargo.toml:
```toml
[workspace.package]
license = "MIT"

[package]
name = "wasm-pack-error"
version = "0.1.0"
edition = "2021"
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
```

- run `wasm-pack build/test`:

```log
Error: failed to parse manifest: /path/to/Cargo.toml
Caused by: invalid type: map, expected a string for key `package.license`
```

- cargo metadata command output is fine:
```sh
$ cargo metadata --format-version 1 | jq -r '.packages[0].license'
MIT
```

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: v0.10.3
rustc version: >=1.64
