### ISSUE TITLE
Cannot Create New Wasm Pack Project

### ISSUE THREAD

**Issue by seanaye** [rustwasm/wasm-pack#1266]
## 🐛 Bug description
`wasm-pack --version`
`> wasm-pack 0.11.0`

`wasm-pack new hello-world`
```
>Error: expected value at line 1 column 1
>Caused by: expected value at line 1 column 1
```

#### 🤔 Expected Behavior
Should create new project in current directory

#### 👟 Steps to reproduce
I tried to update wasm-pack via cargo 
`cargo install wasm-pack`
realized the install was broken, then uninstalled and re-installed via the install script
`cargo uninstall wasm-pack`
`curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh`
This gave me the above error

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: see above
rustc version: rustc 1.69.0-nightly (246eae2fa 2023-02-21)

**Comment by wolkenmachine** [comment]
I'm hitting the same issue. Updated wasm-pack using:
`curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh`

error:
```
> wasm-pack new hello-world
Error: expected value at line 1 column 1
Caused by: expected value at line 1 column 1
```

**Comment by unti1x** [comment]
Confirm. `wasm-pack` v0.11.0 doesn't work, downgrading to 0.10.3 helped

**Comment by Dueen** [comment]
Issue confirmed: Creating new project not working on M1 Macbook.

**Comment by alikulaOwen** [comment]
The fix doesn't work for my Macbook pro m2 any other fixes?

**Comment by LeviticusNelson** [comment]
It might have to do with a bad get request to `https://crates.io/api/v1/crates/{name}` at `Krate::new`:
```
We require that all requests include a `User-Agent` header.  To allow us to determine the impact your bot has on our service, we ask that your user agent actually identify your bot, and not just report the HTTP client library you're using.  Including contact information will also reduce the chance that we will need to take action against your bot.

Bad:
  User-Agent: reqwest/0.9.1

Better:
  User-Agent: my_crawler

Best:
  User-Agent: my_crawler (my_crawler.com/info)
  User-Agent: my_crawler (help@my_crawler.com)

If you believe you've received this message in error, please email help@crates.io and include the request id 53cdcda1-0ea7-4acd-9673-45da30071f07.

```
