### ISSUE TITLE
Segfault when running wasm-pack build

### ISSUE THREAD

**Issue by newcomb-luke** [rustwasm/wasm-pack#1299]
## 🐛 Bug description

I really hope that I am just doing something wrong and it isn't a real problem. But just when I try to run `wasm-pack build` all I get is a segfault. 

#### 🤔 Expected Behavior

I had hoped my crate would be compiled for wasm.

#### 👟 Steps to reproduce

These are the steps that I did to get to this point:

```
cargo install wasm-pack
cargo new --lib wasm-test
cd wasm-test
cargo add wasm-bindgen
```

I edited the Cargo.toml to set the crate type to `cdylib`:

```toml
[package]
name = "wasm-test"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.87"
```

My lib.rs file:

```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn add(a: i32, b: i32) -> i32 {
    a + b
}
```

```
wasm-pack build
fish: Job 1, 'wasm-pack build' terminated by signal SIGSEGV (Address boundary error)
```

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack 0.11.1
rustc 1.70.0 (90c541806 2023-05-31)
