### ISSUE TITLE
Support custom Readme file

### ISSUE THREAD

**Issue by fralonra** [rustwasm/wasm-pack#1306]
## 💡 Feature description
Currently the crate's Readme will be copied during the build proccess.
However, somtimes the npm package might uses a different Readme file from the crate, due to different api etc.
For now the only way to do this is by hand.

#### 💻 Basic example
Introduce a configuation field in Cargo.toml, for example:

```toml
[package.metadata.wasm-pack]
readme = "custom/readme/file"
```

If this field is omitted, use the crate's one.
