### ISSUE TITLE
`wasm-pack build` hangs

### ISSUE THREAD

**Issue by axetroy** [rustwasm/wasm-pack#1476]
## 🐛 Bug description

The command hangs forever

Maybe it's related to [#868](https://github.com/rustwasm/wasm-pack/issues/921#issuecomment-1628408262)

#### 🤔 Expected Behavior

It should build the expected package

#### 👟 Steps to reproduce

```bash
$ wasm-pack build --release --target bundler --scope axetroy --out-dir out
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
    Finished `release` profile [optimized] target(s) in 0.04s

# hangs here forever
```

This is development mode is working

```bash
$ wasm-pack build --dev --target bundler --scope axetroy --out-dir out

# works
```

```toml
[profile.release]
# This makes the compiled code faster and smaller, but it makes compiling slower,
# so it's only enabled in release mode.
lto = true
```

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.13.1
rustc version: 1.84.1 (e71f9a9a9 2025-01-27)
