### ISSUE TITLE
Fails to recognize wasm-bindgen outside of `[dependencies]` in Cargo.toml

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-pack#290]
## 🐛 Bug description

Currently `wasm-pack` will automatically verify that `wasm-bindgen` is listed in your manifest (yay!) but it doesn't catch situations like:

```toml
[target.wasm32-unknown-unknown.dependencies]
wasm-bindgen = "0.2"
```

printing the error:

```
Ensure that you have "wasm-bindgen" as a dependency in your Cargo.toml file:
[dependencies]
wasm-bindgen = "0.2"
```

Projects that support multiple platforms may not always pull `wasm-bindgen` in on all platforms, so this may come up in various libraries that want to use `wasm-pack test` but also want to have a different api for other platforms!
