### ISSUE TITLE
wrong dependency flagged as missing

### ISSUE THREAD

**Issue by yoshuawuyts** [rustwasm/wasm-pack#377]
## 🐛 Bug description
I ran `wasm-pack test` without `wasm-bindgen-test` installed, and got a message about `wasm-bindgen` not being installed instead.

#### 🤔 Expected Behavior
I should have received a warning about `wasm-bindgen-test` not being installed. Instead I had to read through the detailed log below to figure out what was wrong, which is easier to miss.

#### 👟 Steps to reproduce
Given the following `Cargo.toml`
```toml
[package]
name = "my_crate"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
failure = "0.1.2"
wasm-bindgen = "0.2.23"

[dependencies.web-sys]
version = "0.3.0"
features = [
  "Document",
  "EventTarget",
]
```
run
```sh
$ wasm-pack test
```

It will complain about `wasm-bindgen` not existing, but the result will show that `wasm-bindgen-test` is missing.

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.5.0
rustc version: 1.30-nightly

## Screenshot
![2018-09-26-213952_1920x1080](https://user-images.githubusercontent.com/2467194/46104900-e391a280-c1d4-11e8-8b54-9dd0c68bf898.png)
