### ISSUE TITLE
Wasm-pack test –safari –headless driver failed to bind port during startup

### ISSUE THREAD

**Issue by KronicDeth** [rustwasm/wasm-pack#702]
## 🐛 Bug description

`wasm-pack test --safari --headless` works locally, but says `driver failed to bind port during startup` on CircleCI

#### 🤔 Expected Behavior

Testing works locally and on CircleCI.  

I'd be fine with a simple explanation of what I'm missing in the environment setup or something that can be added to the docs here or on CircleCI to make this easier in the future for others.

#### 👟 Steps to reproduce

1. Setup a wasm-pack project
2. `wasm-pack test --safari -headless` in CircleCI using the following config:
   <details>

   ```
   version: 2.1
   executors:
     x86_64_macos:
       macos:
         # a version needs to be picked.  The latest, non-beta was chosen.
         xcode: "10.3.0"
       environment:
         CARGO_HOME: cargo
         HOMEBREW_NO_AUTO_UPDATE: 1
         HOMEBREW_NO_INSTALL_CLEANUP: 1
         LLVM_SYS_70_PREFIX: /usr/local/opt/llvm
   jobs:
     wasm32_safari_examples_spawn_chain_test:
       executor: x86_64_macos
       steps:
         - run:
             name: Enable safari driver
             command: sudo /usr/bin/safaridriver --enable
         - run:
             name: Install LLVM
             command: brew install llvm
         - checkout
         - restore_cache:
             keys:
               - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}-wasm32-safari
         - run:
             name: Install rustup and nightly toolchain
             command: |
               curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain=nightly
               echo 'export PATH=/Users/distiller/project/cargo/bin:$PATH' >> $BASH_ENV
         - run:
             name: Install wasm32 target
             command: rustup target add wasm32-unknown-unknown --toolchain nightly
         - run:
             name: Install wasm-bindgen-cli
             command: cargo +nightly install wasm-bindgen-cli
         - run:
             name: Install wasm-pack
             command: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
         - run:
             name: Run all tests
             command: wasm-pack test --safari --headless
         - save_cache:
             key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}-wasm32-safari
             paths:
               - cargo
               - target/debug/.fingerprint
               - target/debug/build
               - target/debug/deps
   workflows:
     version: 2
     primary:
       jobs:
         - wasm32_safari_test
   ```

   </details>

#### Log

<details>

```
...
Running headless tests in Safari with `/usr/bin/safaridriver`
Spawning Geckodriver...                           
driver status: exit code: 1
error: driver failed to bind port during startup
error: test failed, to rerun pass '--test web'
Error: Running Wasm tests with wasm-bindgen-test failed
Caused by: failed to execute `cargo test`: exited with exit code: 1
Exited with code 1
```

</details>

#### 🌍 Your environment

wasm-pack version: `0.8.1`
rustc version: `1.39.0-nightly (2111aed0a 2019-08-17)`
