### ISSUE TITLE
Support custom section in Cargo.toml, ex. [wasm]

### ISSUE THREAD

**Issue by barabadzhi** [rustwasm/wasm-pack#707]
## 💡 Feature description
 _Prequel:_ The original issue I had faced was `wasm-pack` not pulling `keywords` from `Cargo.toml` into generated `package.json`. This affects the visibility of the package in the registry. The solution so far is manual editing of `package.json` which is not ideal, imho.

 _Idea evolution:_ Why not to add support for a custom `[wasm]` (or `[package.wasm]`) section to `Cargo.toml`? This can be  a set of key/value pairs to put into generated `package.json`. It can even help overriding same-name field from `[package]` specifically for wasm target.

#### 💻 Basic example
```toml
[package]
name = "my-lib" # this name will be used on crates.io
                # package may be used as a native lib without possible confusion
[package.wasm]
name = "my-lib-wasm" # override, this name will be used on npm
keywords = ["one", "two", "three"] # original to generated package.json
```

What do you think?

PS: Would be happy to pick this one up :nerd_face:
