### ISSUE TITLE
Enable use of wasm-pack with panic_immediate_abort

### ISSUE THREAD

**Issue by sffc** [rustwasm/wasm-pack#737]
I'm trying to enable panic_immediate_abort in order to get smaller wasm size (see https://github.com/rust-lang/rust/issues/54981).  The workflow is to create a Xargo.toml file:

```toml
[dependencies]
std = {default-features=false, features=["panic_immediate_abort"]}
```

However, I can't figure out how to invoke `xargo` when using `wasm-pack build`.  I can run `xargo build --target wasm32-unknown-unknown --release`, which I assume puts the output in the *target* directory without compiling it to the *pkg* directory, but then `wasm-pack build` just overwrites the *target* directory again with the non-xargo build.

**Comment by Ngalstyan4** [comment]
I think being able to use `xargo` instead of `cargo` has more general uses as well and has to be supported. For example, using wasm32 simd extensions is currently unstable and requires recompiling libcore in order to enable them so in order to take advantage of these in WebAssembly, one has to recompile libcore, typically done by `xargo`.

**Comment by Pauan** [comment]
Note that it's no longer needed to use xargo, since [`build-std`](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#build-std) is now a part of Rust itself (nightly only):

```
wasm-pack build --release -- -Z build-std=std,panic_abort
```

This works for enabling simd as well. You simply create a `.cargo/config` file in your project which contains this:

```toml
[build]
rustflags = ["-C", "target-feature=+simd128"]
```
