### ISSUE TITLE
wasm-opt fails when using WASM_INTERFACE_TYPES=1

### ISSUE THREAD

**Issue by JesterOrNot** [rustwasm/wasm-pack#793]
## 🐛 Bug description
The webassembly breaks when I have wasm-opt on
![image](https://user-images.githubusercontent.com/50386709/74606839-4ff69580-5099-11ea-8356-3d68b4f51316.png)
I am able to get around the error when I add
```toml
[package.metadata.wasm-pack.profile.dev]
wasm-opt = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = true
```
But It should work even if I add the optimizations.
#### 🤔 Expected Behavior
It still compiles when I use the optimizations
#### 👟 Steps to reproduce
https://github.com/JesterOrNot/markdown_wasi/tree/bug
Run `make` and see the error
#### 🌍 Your environment
Open in the browser https://gitpod.io/#https://github.com/JesterOrNot/markdown_wasi/tree/bug
Include the relevant details of your environment. Gitpod Cloud IDE based on ubuntu docker
wasm-pack version: 0.9.1
rustc version: 1.4.1

**Comment by Pauan** [comment]
To clarify, does it work correctly if you don't use `WASM_INTERFACE_TYPES=1`?

**Comment by JesterOrNot** [comment]
No

**Comment by JesterOrNot** [comment]
The function I'm using is https://github.com/bytecodealliance/wasmtime-demos/blob/master/markdown/src/lib.rs

**Comment by JesterOrNot** [comment]
Try running the function with WASM_INTERFACE_TYPES=1 in the example repo

**Comment by Pauan** [comment]
If it's still erroring even when not using `WASM_INTERFACE_TYPES=1`, then this sounds similar to https://github.com/rustwasm/wasm-pack/issues/696

**Comment by JesterOrNot** [comment]
Just looked through it. But if that was the case it should be fixed right?

**Comment by ratnadeep007** [comment]
Same error here also. Trying to follow tutorial and got this error. 

Also tried adding:
```toml
[package.metadata.wasm-pack.profile.dev]
wasm-opt = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = true
```
Still it doesn't compile. Also tried adding `wasm-opt` from `npm` still failing. When not using `WASM_INTERFACE_TYPES=1` its still failing. Only way around is to add:

```toml
[package.metadata.wasm-pack.profile.release]
wasm-opt = false
```

Hope this issue resolves soon.
