### ISSUE TITLE
wasm-pack randomly uses the wrong package if multiple packages have the same name

### ISSUE THREAD

**Issue by 0xd4d** [rustwasm/wasm-pack#829]
## 🐛 Bug description

If there are 2 packages with the same name, wasm-pack will sometimes use the wrong one and show this error message:

```
Error: crate-type must be cdylib to compile to wasm32-unknown-unknown. Add the following to your Cargo.toml file:

[lib]
crate-type = ["cdylib", "rlib"]
```

#### 🤔 Expected Behavior

The main crate should be used.

#### 👟 Steps to reproduce

`wasm-pack build` until it fails, should not take long.

main wasm crate:

somename1/Cargo.toml

```toml
[package]
authors = ["The wasm-pack developers"]
description = "so awesome rust+wasm package"
license = "WTFPL"
name = "somename"
repository = "https://github.com/rustwasm/wasm-pack.git"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
somenameother = { path = "../somename2", package = "somename" }
```

somename1/src/lib.rs

```rust
pub fn method() -> i32 {
    somenameother::method()
}
```

non-wasm crate:

somename2/Cargo.toml

```toml
[package]
authors = ["The wasm-pack developers"]
description = "so awesome rust+wasm package"
license = "WTFPL"
name = "somename"
repository = "https://github.com/rustwasm/wasm-pack.git"
version = "0.1.1"

[lib]
crate-type = ["rlib"]
```

somename2/src/lib.rs

```rust
pub fn method() -> i32 {
    0
}
```

#### 🌍 Your environment

wasm-pack version: 0.9.1
rustc version: 1.42.0

**Comment by RReverser** [comment]
This actually explains a bug I've been running into as well. Since it was flaky, I was sure it had something to do with Docker or WSL all this time.

Thanks for your report, at least I can work around it now!

**Comment by ufoscout** [comment]
To reproduce this bug, create a new cargo project with an empty `src/lib.rs` file and fill the `Cargo.toml` with:
```toml
[package]
name = "yew"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
yew = "0.16.2"
```

then run: `wasm-pack build --target web --out-name wasm`

In my case, half of the times the build fails with:
```
Error: crate-type must be cdylib to compile to wasm32-unknown-unknown. Add the following to your Cargo.toml file:

[lib]
crate-type = ["cdylib", "rlib"]
```

If you change `name = "yew"` in the Cargo [package] section to `name = "WHATEVER_YOU_WANT"` the bug disappears. So it seems that the problem is caused by the fact that the package name is equal to the name of a dependency.

My system:
OS: ubuntu 20.04 64 bit
rustc --version: rustc 1.43.1 (8d69840ab 2020-05-04)
wasm-pack --version: wasm-pack 0.9.1
