### ISSUE TITLE
wasm-opt Tool version should be bumped 

### ISSUE THREAD

**Issue by michelhe** [rustwasm/wasm-pack#919]
## 🐛 Bug description
The prebuilt wasm-opt version_90 segfaults when optimizing my crate with `-enable-mutable-globals`.
When I manually use version_97, it works 

I think it will also help fix #886 

#### 👟 Steps to reproduce
I didn't try to test any other project, but It specifically segfaults in mine: https://github.com/michelhe/rustboyadvance-ng/tree/master/platform/rustboyadvance-wasm
add to Cargo.toml
```toml
[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals"]
```
run `wasm-pack build --release`

#### 🌍 Your environment
wasm-pack version: 0.9.1
rustc version: rustc 1.43.0 (4fb7144ed 2020-04-20)
